---
- hosts: localhost
  sudo: yes
  tasks:
    - shell: echo "hello world"
  roles :
    - common
    - andrewrothstein.hub
#    - {role: geerlingguy.docker, docker_users: [fdume], docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"}
    - {role: geerlingguy.docker, docker_users: [fdume], docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} bionic {{ docker_apt_release_channel }}"}
