---
- name: Install list of packages
  apt: pkg={{item}} state=present
  with_items:
    - git
    - git-extras
    - tmux
    - tmate
    - httpie
    - firefox-locale-fr
    - graphviz
    - make
    - mdp		
#    - mongo-tools
#    - mongodb-clients
    - nmap
    - gparted
    - php
    - php-xml
    - php-json
    - pssh
    - rsync
    - wget
    - youtube-dl 
# to manage password
    - keepassxc
    - chromium-browser
    - htop
# nfs support for Vagrant
    - nfs-kernel-server
    - nfs-common
    - portmap
    - curl
# to manage gnome shell extensions
    - chrome-gnome-shell
# flatpak to install sparkleshare
    - flatpak
# optimisation de la batterie
# source : https://medium.com/@hkdb/ubuntu-18-04-on-lenovo-x1-carbon-6g-d99d5667d4d5
# Vérifier qu'il est bien démarré
# sudo tlp start
# sudo systemctl enable tlp
# sudo systemctl enable tlp-sleep
    - tlp
    - tlp-rdw
    - acpi-call-dkms
    - tp-smapi-dkms
#    - acpi-call-dkms
# support pour exfat
    - exfat-fuse
    - exfat-utils
    - xterm
    - gnome-tweaks
    - # ab & co
    - apache2-utils
    - net-tools
    - traceroute
    - oathtool
    - vim
    - lolcat
# to capture your screen and create gif
    - peek
  become: true    

- name: Install "{{item}}" with option --classic
  command: snap install {{item}} --classic
  become: true
  with_items:
    - phpstorm
    - insomnia
    - spotify
    - sublime-text
    - postman
    - skype
    - asciicinema
    - chezmoi

- name: Install lsix
  get_url:
    url: https://raw.githubusercontent.com/hackerb9/lsix/master/lsix
    dest: /usr/local/bin/lsix
    mode: 0755

- name: Install notable-1.8.4
  apt:
    deb: https://github.com/fabiospampinato/notable/releases/download/v1.8.4/notable_1.8.4_amd64.deb

# Cross-platform application to open any website or media in a floating window
# https://github.com/kamranahmedse/pennywise
#- name: Install pennywise-0.6.3
#  apt:
#    deb: https://github.com/kamranahmedse/pennywise/releases/download/v0.6.3/pennywise_0.6.3_amd64.deb

#- name: Install chezmoi to manage dotfiles
#  apt:
#    deb: https://github.com/twpayne/chezmoi/releases/download/v1.8.0/chezmoi_1.5.6-891_linux_amd64.deb
#    only_upgrade: yes

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install the Sparkleshare package from flathub for current user
  flatpak:
    name: org.sparkleshare.SparkleShare
    state: present
